name: nethive_neo
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.4 <4.0.0"
  

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  intl: ^0.19.0  # Volver a la versiÃ³n compatible con flutter_localizations
  go_router: ^14.6.2
  dio: ^5.7.0
  supabase_flutter: ^1.10.25
  flutter_secure_storage: ^9.2.4
  pluto_grid: ^8.0.0
  google_fonts: ^6.2.1
  google_maps: ^6.3.0
  gap: ^3.0.1
  dart_jsonwebtoken: ^2.17.0
  uuid: ^4.5.1
  image_picker: ^1.1.2
  fluttertoast: ^8.2.8
  provider: ^6.1.1
  random_password_generator: ^0.2.1
  email_validator: ^3.0.0
  file_picker: ^8.0.5
  flutter_side_menu: ^0.4.0
  auto_size_text: ^3.0.0
  url_launcher: ^6.2.0
  url_strategy: ^0.2.0
  flutter_portal: ^1.1.4
  flutter_localizations:
    sdk: flutter

  # Mapa interactivo
  flutter_map: ^7.0.2
  latlong2: ^0.9.1

  # Paquetes adicionales del pubspec.yaml que te proporcionaron
  animated_toggle_switch: ^0.8.2
  another_stepper: ^1.2.2
  buttons_tabbar: ^1.3.8
  carousel_slider: ^5.0.0
  chip_list: ^3.0.0
  countries_world_map: ^1.1.1
  customizable_counter: ^1.0.4
  drop_down_list_menu: ^0.0.9
  fl_chart: ^0.69.0
  fl_heatmap: ^0.4.4
  flip_card: ^0.7.0
  flutter_credit_card: ^4.0.1
  calendar_date_picker2: ^1.0.4
  flutter_spinkit: ^5.2.0
  flutter_tts: ^4.0.2
  http: ^1.2.2
  mask_text_input_formatter: ^2.8.0
  path: ^1.8.3
  percent_indicator: ^4.2.3
  pretty_qr_code: ^3.3.0
  screenshot: ^3.0.0
  shared_preferences: ^2.2.2
  toggle_switch: ^2.3.0
  responsive_builder: ^0.7.1
  tab_container: ^3.5.3
  group_button: ^5.3.4
  flutter_graph_view: ^1.1.6
  flutter_animate: ^4.2.0
  flutter_flow_chart: 3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

dependency_overrides:
  intl: ^0.19.0  # Override para que pluto_grid funcione

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/
    - assets/referencia/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
